### ISSUE TITLE
Push notification settings

### ISSUE THREAD

**Issue by yoshida-git-ai** [immanuelfodor/rocketchat-push-gateway#6]
All push notifications in Rocketchat with ``rocketchat-push-gateway''
What is the way to make it work with ?

I can build the Apprise GUI with Docker and display the UI

And you can see Mongo's Raix Push App Tokens in the metabase

Looks like you're using GCM now

I'm looking for a way to make push notifications work in a completely ”closed network”

**Comment by immanuelfodor** [comment]
There is absolutely no GCM involved in the push gateway, it just uses the GCM token from the Android app to identify the push targets. The push service is provided by Gotify which uses websockets as communication channel to display the push notifications. If the network diagram in the readme is completely isolated on a private LAN, it will still work. I think the answers you are looking for are in understanding Gotify more: https://gotify.net/

```
                                   +------------+
                                   |            |
                      +----------->+ RocketChat |
                      |            |            |
                      |            +-----+------+
                      |                  |
         +------------+--+               v
   SSL   |               |        +------+-------+
+------->+ Reverse proxy |        |              |
         |               |        | Push gateway |
         +------------+--+        |              |
                      |           +-----------+--+
                      |                       |
                      |                       v
                      |                 +-----+----+
                      |                 |          |
                      +---------------->+  Gotify  |
                                        |          |
                                        +----------+
```
